title: clouds-blog
description: clouds-blog
theme: "just-the-docs"
favicon_ico: "/assets/images/favicon.ico"
footer_content: "Copyright &copy; 2023 clouds"


url: https://szclouds.github.io/

aux_links:
  Repository: https://github.com/szclouds/szclouds.github.io/
